# Generated by Django 3.1.4 on 2020-12-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selfie_video',
            field=models.CharField(default=False, max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='camera_1',
            field=models.CharField(default=False, max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='camera_2',
            field=models.CharField(default=False, max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='camera_3',
            field=models.CharField(default=False, max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.CharField(default=False, max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.CharField(default=False, max_length=254),
        ),
    ]
