# Generated by Django 3.1.4 on 2020-12-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201224_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='release',
            new_name='release_date',
        ),
        migrations.AddField(
            model_name='product',
            name='release_year',
            field=models.IntegerField(default=False),
        ),
    ]
