# Generated by Django 3.1.4 on 2020-12-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201228_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='camera_4',
            field=models.CharField(default=False, max_length=254),
        ),
    ]
