# Generated by Django 3.1.4 on 2021-01-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210111_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.CharField(default='Black', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='hex_colour',
            field=models.CharField(default='#000000', max_length=100),
        ),
    ]
