# Generated by Django 3.1.4 on 2021-02-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210120_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='card',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unfriendly_name',
            field=models.CharField(default=False, max_length=254),
        ),
    ]
