# Generated by Django 3.1.4 on 2021-02-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210201_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selfie_camera',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
