# Generated by Django 3.1.4 on 2021-02-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_selfie_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_front',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='image_rear',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
