# Generated by Django 3.1.4 on 2021-02-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210204_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_display',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
