# Generated by Django 3.1.4 on 2021-02-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_image_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colour',
            field=models.TextField(default='Black', max_length=100),
        ),
    ]
