# Generated by Django 3.2 on 2021-04-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210222_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unfriendly_colour',
            field=models.TextField(default='Black', max_length=100),
        ),
    ]
